/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#ffb0cc',
        'outline-variant': '#e4bdc2',
        'secondary': '#a82d68',
        'primary-fixed': '#ffd9de',
        'primary': '#b80049',
        'inverse-on-surface': '#f1f1f1',
        'error-container': '#ffdad6',
        'tertiary-container': '#008644',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'on-primary-fixed': '#400014',
        'on-secondary-fixed-variant': '#890f50',
        'on-tertiary': '#ffffff',
        'background': '#f9f9f9',
        'secondary-fixed': '#ffd9e4',
        'surface': '#f9f9f9',
        'tertiary-fixed': '#89faa8',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f3131',
        'inverse-primary': '#ffb2be',
        'on-secondary-fixed': '#3e0020',
        'on-error': '#ffffff',
        'surface-container': '#eeeeee',
        'surface-bright': '#f9f9f9',
        'on-tertiary-container': '#f6fff3',
        'tertiary': '#006a34',
        'surface-variant': '#e2e2e2',
        'surface-dim': '#dadada',
        'on-primary-fixed-variant': '#900038',
        'primary-fixed-dim': '#ffb2be',
        'surface-tint': '#bc004b',
        'on-background': '#1a1c1c',
        'tertiary-fixed-dim': '#6ddd8e',
        'on-secondary-container': '#740041',
        'outline': '#8f6f73',
        'secondary-container': '#ff73ae',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#5b3f43',
        'error': '#ba1a1a',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary-fixed': '#00210c',
        'on-tertiary-fixed-variant': '#005227',
        'surface-container-low': '#f3f3f3',
        'on-error-container': '#93000a',
        'on-surface': '#1a1c1c',
        'primary-container': '#e2165f',
        'on-primary-container': '#fffbff',
      },
      fontFamily: {
        'headline': ['Epilogue', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}